set_property SRC_FILE_INFO {cfile:/media/saad/NVMe2/UnderwaterModem/Updated_MyXilinx/3_Simple_HW/SDUAM.srcs/constrs_1/new/SDUAMconstraints.xdc rfile:../../../SDUAM.srcs/constrs_1/new/SDUAMconstraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN A20 IOSTANDARD LVCMOS33} [get_ports ADCclock]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M20 IOSTANDARD LVCMOS33} [get_ports {ADCdata[14]}]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M19 IOSTANDARD LVCMOS33} [get_ports {ADCdata[13]}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L20 IOSTANDARD LVCMOS33} [get_ports {ADCdata[12]}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L19 IOSTANDARD LVCMOS33} [get_ports {ADCdata[11]}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J20 IOSTANDARD LVCMOS33} [get_ports {ADCdata[10]}]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J19 IOSTANDARD LVCMOS33} [get_ports {ADCdata[9]}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G20 IOSTANDARD LVCMOS33} [get_ports {ADCdata[8]}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G19 IOSTANDARD LVCMOS33} [get_ports {ADCdata[7]}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F20 IOSTANDARD LVCMOS33} [get_ports {ADCdata[6]}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F19 IOSTANDARD LVCMOS33} [get_ports {ADCdata[5]}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D20 IOSTANDARD LVCMOS33} [get_ports {ADCdata[4]}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN D19 IOSTANDARD LVCMOS33} [get_ports {ADCdata[3]}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN C20 IOSTANDARD LVCMOS33} [get_ports {ADCdata[2]}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B20 IOSTANDARD LVCMOS33} [get_ports {ADCdata[1]}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B19 IOSTANDARD LVCMOS33} [get_ports {ADCdata[0]}]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N20 IOSTANDARD LVCMOS33 DRIVE 4 SLEW SLOW} [get_ports DACclock]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y16 IOSTANDARD LVCMOS33 DRIVE 4 SLEW SLOW} [get_ports DACsleep]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P19 IOSTANDARD LVCMOS33 DRIVE 4 SLEW SLOW} [get_ports {DACdata[13]}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P20 IOSTANDARD LVCMOS33 DRIVE 4 SLEW SLOW} [get_ports {DACdata[12]}]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R19 IOSTANDARD LVCMOS33 DRIVE 4 SLEW SLOW} [get_ports {DACdata[11]}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVCMOS33 DRIVE 4 SLEW SLOW} [get_ports {DACdata[10]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T19 IOSTANDARD LVCMOS33 DRIVE 4 SLEW SLOW} [get_ports {DACdata[9]}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U20 IOSTANDARD LVCMOS33 DRIVE 4 SLEW SLOW} [get_ports {DACdata[8]}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V20 IOSTANDARD LVCMOS33 DRIVE 4 SLEW SLOW} [get_ports {DACdata[7]}]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W20 IOSTANDARD LVCMOS33 DRIVE 4 SLEW SLOW} [get_ports {DACdata[6]}]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS33 DRIVE 4 SLEW SLOW} [get_ports {DACdata[5]}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVCMOS33 DRIVE 4 SLEW SLOW} [get_ports {DACdata[4]}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W18 IOSTANDARD LVCMOS33 DRIVE 4 SLEW SLOW} [get_ports {DACdata[3]}]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33 DRIVE 4 SLEW SLOW} [get_ports {DACdata[2]}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS33 DRIVE 4 SLEW SLOW} [get_ports {DACdata[1]}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y17 IOSTANDARD LVCMOS33 DRIVE 4 SLEW SLOW} [get_ports {DACdata[0]}]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property IOB TRUE [get_ports {DACdata[*]}]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N18 IOSTANDARD LVCMOS33 DRIVE 4 SLEW SLOW} [get_ports PowerAmpEnable]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/m_axis_data_tdata[0]}]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/m_axis_data_tdata[17]}]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/m_axis_data_tdata[3]}]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/m_axis_data_tdata[6]}]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/m_axis_data_tdata[19]}]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/m_axis_data_tdata[7]}]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/m_axis_data_tdata[13]}]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/m_axis_data_tdata[8]}]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/m_axis_data_tdata[10]}]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/m_axis_data_tdata[11]}]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/m_axis_data_tdata[20]}]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/s_axis_data_tdata[8]}]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/s_axis_data_tdata[31]}]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/s_axis_data_tdata[17]}]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/m_axis_data_tdata[22]}]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/m_axis_data_tdata[30]}]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/s_axis_data_tdata[29]}]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/s_axis_data_tdata[21]}]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/s_axis_data_tdata[3]}]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/s_axis_data_tdata[10]}]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/m_axis_data_tdata[26]}]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/s_axis_data_tdata[5]}]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/s_axis_data_tdata[23]}]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/s_axis_data_tdata[14]}]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/s_axis_data_tdata[26]}]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/s_axis_data_tdata[19]}]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/s_axis_data_tdata[25]}]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/m_axis_data_tdata[16]}]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/m_axis_data_tdata[4]}]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/m_axis_data_tdata[12]}]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/m_axis_data_tdata[15]}]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/m_axis_data_tdata[1]}]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/m_axis_data_tdata[14]}]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/m_axis_data_tdata[2]}]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/m_axis_data_tdata[5]}]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/m_axis_data_tdata[18]}]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/m_axis_data_tdata[9]}]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/s_axis_data_tdata[0]}]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/m_axis_data_tdata[21]}]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/s_axis_data_tdata[28]}]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/s_axis_data_tdata[30]}]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/m_axis_data_tdata[29]}]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/s_axis_data_tdata[12]}]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/s_axis_data_tdata[20]}]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/s_axis_data_tdata[4]}]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/m_axis_data_tdata[23]}]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/s_axis_data_tdata[1]}]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/s_axis_data_tdata[13]}]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/s_axis_data_tdata[7]}]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/s_axis_data_tdata[18]}]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/m_axis_data_tdata[24]}]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/m_axis_data_tdata[25]}]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/s_axis_data_tdata[2]}]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/s_axis_data_tdata[15]}]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/s_axis_data_tdata[16]}]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/s_axis_data_tdata[6]}]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/s_axis_data_tdata[22]}]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/s_axis_data_tdata[24]}]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/m_axis_data_tdata[27]}]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/s_axis_data_tdata[27]}]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/s_axis_data_tdata[9]}]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/m_axis_data_tdata[28]}]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/m_axis_data_tdata[31]}]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_30kHz/s_axis_data_tdata[11]}]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets SDUAM_i/FIR_30kHz/m_axis_data_tvalid]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_40kHz/m_axis_data_tdata[2]}]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_40kHz/m_axis_data_tdata[0]}]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_40kHz/m_axis_data_tdata[18]}]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_40kHz/m_axis_data_tdata[19]}]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_40kHz/m_axis_data_tdata[26]}]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_40kHz/m_axis_data_tdata[12]}]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_40kHz/m_axis_data_tdata[25]}]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_40kHz/m_axis_data_tdata[13]}]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_40kHz/m_axis_data_tdata[1]}]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_40kHz/m_axis_data_tdata[27]}]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_40kHz/m_axis_data_tdata[29]}]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_40kHz/m_axis_data_tdata[17]}]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_40kHz/m_axis_data_tdata[21]}]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_40kHz/m_axis_data_tdata[3]}]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_40kHz/m_axis_data_tdata[4]}]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_40kHz/m_axis_data_tdata[16]}]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_40kHz/m_axis_data_tdata[23]}]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_40kHz/m_axis_data_tdata[5]}]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_40kHz/m_axis_data_tdata[22]}]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_40kHz/m_axis_data_tdata[6]}]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_40kHz/m_axis_data_tdata[7]}]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_40kHz/m_axis_data_tdata[30]}]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_40kHz/m_axis_data_tdata[31]}]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_40kHz/m_axis_data_tdata[8]}]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_40kHz/m_axis_data_tdata[20]}]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_40kHz/m_axis_data_tdata[9]}]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_40kHz/m_axis_data_tdata[28]}]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_40kHz/m_axis_data_tdata[15]}]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_40kHz/m_axis_data_tdata[14]}]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_40kHz/m_axis_data_tdata[10]}]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_40kHz/m_axis_data_tdata[11]}]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {SDUAM_i/FIR_40kHz/m_axis_data_tdata[24]}]
