# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/SDUAMconstraints.xdc

# Block Designs: bd/SDUAM/SDUAM.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SDUAM || ORIG_REF_NAME==SDUAM} -quiet] -quiet

# IP: bd/SDUAM/ip/SDUAM_processing_system7_0_0/SDUAM_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SDUAM_processing_system7_0_0 || ORIG_REF_NAME==SDUAM_processing_system7_0_0} -quiet] -quiet

# IP: bd/SDUAM/ip/SDUAM_rst_ps7_0_100M_0/SDUAM_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SDUAM_rst_ps7_0_100M_0 || ORIG_REF_NAME==SDUAM_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/SDUAM/ip/SDUAM_ps7_0_axi_periph_0/SDUAM_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SDUAM_ps7_0_axi_periph_0 || ORIG_REF_NAME==SDUAM_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/SDUAM/ip/SDUAM_axi_gpio_0_0/SDUAM_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SDUAM_axi_gpio_0_0 || ORIG_REF_NAME==SDUAM_axi_gpio_0_0} -quiet] -quiet

# IP: bd/SDUAM/ip/SDUAM_system_ila_0_1/SDUAM_system_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SDUAM_system_ila_0_1 || ORIG_REF_NAME==SDUAM_system_ila_0_1} -quiet] -quiet

# IP: bd/SDUAM/ip/SDUAM_auto_pc_0/SDUAM_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SDUAM_auto_pc_0 || ORIG_REF_NAME==SDUAM_auto_pc_0} -quiet] -quiet

# XDC: /media/saad/NVMe2/UnderwaterModem/Updated_MyXilinx/3_Simple_HW/SDUAM.gen/sources_1/bd/SDUAM/SDUAM_ooc.xdc
