#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Oct 04 14:48:53 EDT 2021
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 36633725ee4c4672934ce54b8ea36d6b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot clock_divider_tb_behav xil_defaultlib.clock_divider_tb -log elaborate.log"
xelab -wto 36633725ee4c4672934ce54b8ea36d6b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot clock_divider_tb_behav xil_defaultlib.clock_divider_tb -log elaborate.log

