# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Projects/FAU-Modem/OFDM/Xilinx/Vivado/Simple_HW/SDUAM.srcs/sources_1/bd/SDUAM/ip/SDUAM_axi_gpio_0_0/SDUAM_axi_gpio_0_0.xci
# IP: The module: 'SDUAM_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/FAU-Modem/OFDM/Xilinx/Vivado/Simple_HW/SDUAM.gen/sources_1/bd/SDUAM/ip/SDUAM_axi_gpio_0_0/SDUAM_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'SDUAM_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Projects/FAU-Modem/OFDM/Xilinx/Vivado/Simple_HW/SDUAM.gen/sources_1/bd/SDUAM/ip/SDUAM_axi_gpio_0_0/SDUAM_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SDUAM_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Projects/FAU-Modem/OFDM/Xilinx/Vivado/Simple_HW/SDUAM.gen/sources_1/bd/SDUAM/ip/SDUAM_axi_gpio_0_0/SDUAM_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'SDUAM_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Projects/FAU-Modem/OFDM/Xilinx/Vivado/Simple_HW/SDUAM.srcs/sources_1/bd/SDUAM/ip/SDUAM_axi_gpio_0_0/SDUAM_axi_gpio_0_0.xci
# IP: The module: 'SDUAM_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/FAU-Modem/OFDM/Xilinx/Vivado/Simple_HW/SDUAM.gen/sources_1/bd/SDUAM/ip/SDUAM_axi_gpio_0_0/SDUAM_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'SDUAM_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Projects/FAU-Modem/OFDM/Xilinx/Vivado/Simple_HW/SDUAM.gen/sources_1/bd/SDUAM/ip/SDUAM_axi_gpio_0_0/SDUAM_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SDUAM_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Projects/FAU-Modem/OFDM/Xilinx/Vivado/Simple_HW/SDUAM.gen/sources_1/bd/SDUAM/ip/SDUAM_axi_gpio_0_0/SDUAM_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'SDUAM_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
