webtalk_init -webtalk_dir /home/saad/Xilinx/2UnderwaterModem/MyXilinx/SDUAM/HW_Ver_less_ILAs/SDUAM.tmp/Clock_Divider_v1_0_project/Clock_Divider_v1_0_project.sim/sim_1/behav/xsim/xsim.dir/clock_divider_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Oct  4 14:48:55 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a5127876-ee23-44e6-9b9d-06935c331a13" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "36633725ee4c4672934ce54b8ea36d6b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Linuxmint" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Linux Mint 20.1" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2024.630 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "8" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "18 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "2 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "6" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.42_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "281032_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2841719073 -regid "" -xml /home/saad/Xilinx/2UnderwaterModem/MyXilinx/SDUAM/HW_Ver_less_ILAs/SDUAM.tmp/Clock_Divider_v1_0_project/Clock_Divider_v1_0_project.sim/sim_1/behav/xsim/xsim.dir/clock_divider_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/saad/Xilinx/2UnderwaterModem/MyXilinx/SDUAM/HW_Ver_less_ILAs/SDUAM.tmp/Clock_Divider_v1_0_project/Clock_Divider_v1_0_project.sim/sim_1/behav/xsim/xsim.dir/clock_divider_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/saad/Xilinx/2UnderwaterModem/MyXilinx/SDUAM/HW_Ver_less_ILAs/SDUAM.tmp/Clock_Divider_v1_0_project/Clock_Divider_v1_0_project.sim/sim_1/behav/xsim/xsim.dir/clock_divider_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
