# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/saad/Xilinx/UnderwaterModem/Updated_MyXilinx/3Vivado_HW/SDUAM.srcs/sources_1/bd/SDUAM/ip/SDUAM_auto_pc_4/SDUAM_auto_pc_4.xci
# IP: The module: 'SDUAM_auto_pc_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/saad/Xilinx/UnderwaterModem/Updated_MyXilinx/3Vivado_HW/SDUAM.gen/sources_1/bd/SDUAM/ip/SDUAM_auto_pc_4/SDUAM_auto_pc_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SDUAM_auto_pc_4'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/saad/Xilinx/UnderwaterModem/Updated_MyXilinx/3Vivado_HW/SDUAM.srcs/sources_1/bd/SDUAM/ip/SDUAM_auto_pc_4/SDUAM_auto_pc_4.xci
# IP: The module: 'SDUAM_auto_pc_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/saad/Xilinx/UnderwaterModem/Updated_MyXilinx/3Vivado_HW/SDUAM.gen/sources_1/bd/SDUAM/ip/SDUAM_auto_pc_4/SDUAM_auto_pc_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SDUAM_auto_pc_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
